/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistasFenix;
import dao.PagoDAO;
import java.math.BigDecimal;
import models.Pago;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

import controlador.Cregistro_clientes;

/**
 *
 * @author Asus
 */
public class registrar_pago extends javax.swing.JInternalFrame {
private PagoDAO pagoDAO;

private void cargarClientes() {
    List<String> clientes = pagoDAO.obtenerUsuarios();
    jComboBox1.removeAllItems();
    for (String cliente : clientes) {
        jComboBox1.addItem(cliente);
    }
}

    /**
     * Creates new form registrar_pago
     */
     private javax.swing.ButtonGroup grupo1 = new javax.swing.ButtonGroup();
    private javax.swing.ButtonGroup grupo2 = new javax.swing.ButtonGroup();
    private boolean programmaticChange = false;
    public registrar_pago() {
        initComponents();
        pagoDAO = new PagoDAO();
        cargarClientes();

        Cregistro_clientes clientes = new Cregistro_clientes();
        ccbcliente_regpago.removeAllItems();
        ccbcliente_regpago.addItem("Selecciona un cliente");
        for (String nombre : clientes.nombres) {
            ccbcliente_regpago.addItem(nombre);
        }
         grupo1.add(rdb_si);
        grupo1.add(rdb_no);
        grupo2.add(rdb_si2);
        grupo2.add(rdb_no2);

        // Ocultar al iniciar
        lbl_pago_completo.setVisible(false);
        rdb_si2.setVisible(false);
        rdb_no2.setVisible(false);
        lbl_cant_pagada.setVisible(false);
        txt_cantidad.setVisible(false);

        // Mostrar los segundos radios cuando se selecciona "Sí" del primero
        rdb_si.addActionListener(e -> {
            if (rdb_si.isSelected()) {
                lbl_pago_completo.setVisible(true);
                rdb_si2.setVisible(true);
                rdb_no2.setVisible(true);
            }
        });

        // Ocultar si se selecciona "No" del primero
        rdb_no.addActionListener(e -> {
            lbl_pago_completo.setVisible(false);
            rdb_si2.setVisible(false);
            rdb_no2.setVisible(false);
            lbl_cant_pagada.setVisible(false);
            txt_cantidad.setVisible(false);
            grupo2.clearSelection(); // desmarca los radios del segundo grupo
        });

        // Mostrar campos cuando se selecciona "No" del segundo grupo
        rdb_no2.addActionListener(e -> {
            if (rdb_no2.isSelected()) {
                lbl_cant_pagada.setVisible(true);
                txt_cantidad.setVisible(true);
            }
        });

        // Ocultar campos cuando se selecciona "Sí" del segundo grupo
        rdb_si2.addActionListener(e -> {
            if (rdb_si2.isSelected()) {
                lbl_cant_pagada.setVisible(false);
                txt_cantidad.setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ccbcliente_regpago = new javax.swing.JComboBox<>();
        lbl_pago = new javax.swing.JLabel();
        rdb_si = new javax.swing.JRadioButton();
        rdb_no = new javax.swing.JRadioButton();
        lbl_pago_completo = new javax.swing.JLabel();
        rdb_si2 = new javax.swing.JRadioButton();
        rdb_no2 = new javax.swing.JRadioButton();
        txt_cantidad = new javax.swing.JTextField();
        lbl_cant_pagada = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel1.setText("Registrar pago");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona el cliente ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
        ccbcliente_regpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ccbcliente_regpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbcliente_regpagoActionPerformed(evt);
            }
        });

        lbl_pago.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        lbl_pago.setText("¿El cliente pago?");

        rdb_si.setText("Si");
        rdb_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_siActionPerformed(evt);
            }
        });

        rdb_no.setText("No");
        rdb_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_noActionPerformed(evt);
            }
        });

        lbl_pago_completo.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        lbl_pago_completo.setText("¿Hizo su pago completo?");

        rdb_si2.setText("Si");

        rdb_no2.setText("No");

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingresa la cantidad pagada");
        lbl_cant_pagada.setText("Ingresa la cantidad pagada");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFenix/confirmar.png"))); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFenix/fenix 128px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lbl_pago))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_cant_pagada)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdb_si2)
                                        .addGap(79, 79, 79)
                                        .addComponent(rdb_no2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdb_si)
                                        .addGap(79, 79, 79)
                                        .addComponent(rdb_no))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbl_pago_completo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ccbcliente_regpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ccbcliente_regpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_pago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb_si)
                            .addComponent(rdb_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_pago_completo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb_si2)
                            .addComponent(rdb_no2))
                        .addGap(1, 1, 1)
                        .addComponent(lbl_cant_pagada))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_noActionPerformed

    private void ccbcliente_regpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbcliente_regpagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccbcliente_regpagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String seleccionado = (String) ccbcliente_regpago.getSelectedItem();
        // Validar selección
        if (seleccionado.equals("Selecciona un cliente")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente de la lista");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pago registrado con éxito");
            jButton1.addActionListener(e -> {
            // Limpiar campos y restablecer todo
           
            
            // Ocultar todo lo secundario
            lbl_pago_completo.setVisible(false);
            rdb_si2.setVisible(false);
            rdb_no2.setVisible(false);
            lbl_cant_pagada.setVisible(false);
            txt_cantidad.setVisible(false);
        });
            // Aquí puedes agregar lo que necesites hacer después
        }
        ccbcliente_regpago.setSelectedIndex(0);
            txt_cantidad.setText("");
            grupo1.clearSelection();
            grupo2.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdb_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_siActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: String clienteSeleccionado = (String) jComboBox1.getSelectedItem();
     PagoDAO pagoDAO = new PagoDAO();

    // Obtener el cliente seleccionado del combo
    String clienteSeleccionado = (String) jComboBox1.getSelectedItem(); 

    if (clienteSeleccionado == null || clienteSeleccionado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecciona un cliente antes de registrar el pago.");
        return;
    }

    // Obtener el ID del cliente
    int idUsuario = pagoDAO.obtenerIdUsuarioPorNombre(clienteSeleccionado);

    if (idUsuario == -1) {
        JOptionPane.showMessageDialog(this, "No se encontró el cliente seleccionado.");
        return;
    }

    // Obtener el monto
    double montoPagado;
    try {
        montoPagado = Double.parseDouble(jTextField1.getText()); 
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un monto válido.");
        return;
    }

    //Crear objeto Pago
    Pago pago = new Pago(idUsuario, BigDecimal.valueOf(montoPagado), LocalDate.now());

    //Registrar en la base de datos
    if (pagoDAO.registrarPago(pago)) {
        JOptionPane.showMessageDialog(this, "Pago registrado exitosamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar el pago.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ccbcliente_regpago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_cant_pagada;
    private javax.swing.JLabel lbl_pago;
    private javax.swing.JLabel lbl_pago_completo;
    private javax.swing.JRadioButton rdb_no;
    private javax.swing.JRadioButton rdb_no2;
    private javax.swing.JRadioButton rdb_si;
    private javax.swing.JRadioButton rdb_si2;
    private javax.swing.JTextField txt_cantidad;
    // End of variables declaration//GEN-END:variables
}
